/**
 * Shows the task overlay with detailed task information.
 * @async
 * @param {string} taskTitle task Title.
 * @param {string} taskDescription task Description.
 * @param {string} taskDueDate task Due Date.
 * @param {string} taskPriority task Priority.
 * @param {Array} taskAssignees task Assignees.
 * @param {string} taskType Task category label.
 * @param {string} subtaskHTML Rendered subtask markup.
 * @param {string} id Database or DOM identifier.
 * @param {string[]} editSubtask Editable subtask labels.
 * @param {Object} taskCreator Saved creator metadata.
 * @param {boolean} aiGenerated Whether the task was generated by AI.
 * @param {Array<*>} attachments Images with their saved metadata and base64 data.
 * @returns {Promise<void>} Resolves when the operation is complete.
 */
async function showOverlay1(taskTitle, taskDescription, taskDueDate, taskPriority, taskAssignees, taskType, subtaskHTML, id, editSubtask, taskCreator, aiGenerated, attachments = []) {
    viewerAttachments = Array.isArray(attachments) ? attachments : [];
    const overlay = document.getElementById("overlay");
    const overlayContent = document.querySelector(".overlayContent");
    overlayContent.innerHTML = buildTaskOverlayHTML(taskTitle, taskDescription,
        taskDueDate, taskPriority, taskAssignees, taskType, subtaskHTML, id,
        taskCreator, aiGenerated, attachments);
    overlayContent.setAttribute('aria-label', 'Task details');
    revealTaskOverlay(overlay, overlayContent);
    await includeHTML();
    showInitials();
    activateTaskDialog(overlayContent);
}

/** Builds the complete task-detail overlay markup.
 * @param {string} title title.
 * @param {string} description description.
 * @param {string} date date.
 * @param {string} priority priority.
 * @param {Array<*>} assignees assignees.
 * @param {string} type type.
 * @param {string} subtasks subtasks.
 * @param {string} id Database or DOM identifier.
 * @param {Object} creator creator.
 * @param {boolean} aiGenerated Whether the task was generated by AI.
 * @param {Array<*>} attachments Images with their saved metadata and base64 data.
 * @returns {string} Rendered markup or text.
 */
function buildTaskOverlayHTML(title, description, date, priority, assignees,
    type, subtasks, id, creator, aiGenerated, attachments) {
    return getOverlayTemplate(title, description, date, priority,
        getPriorityIcon(priority), type, type === 'User Story' ? '#1FD7C1' : '',
        getOverlayAssignees(assignees), subtasks, id, creator, aiGenerated, attachments);
}

/** Builds the assignee rows used in the task-detail overlay.
 * @param {Array<*>} assignees assignees.
 * @returns {*} get overlay assignees result.
 */
function getOverlayAssignees(assignees) {
    if (!Array.isArray(assignees)) return '';
    const assigneeRows = assignees.map(assignee => getOverlayAssigneeHTML(assignee)).join('');
    return `<div class="task-overlay-assignees">${assigneeRows}</div>`;
}

/** Builds one task-detail assignee row.
 * @param {*} assignee assignee.
 * @returns {string} Rendered markup or text.
 */
function getOverlayAssigneeHTML(assignee) {
    const contact = contacts.find(item => item.id === assignee.id);
    if (!contact) return '';
    return renderHtmlTemplate('overlayAssigneeHTMLTemplate', [safeTaskColor(contact.profileColor), getContactAvatarHTML(contact), escapeTaskText(getContactDisplayName(contact))]);
}

/** Makes the task-detail overlay visible.
 * @param {*} overlay overlay.
 * @param {*} content content.
 * @returns {void}
 */
function revealTaskOverlay(overlay, content) {
    content.style.transform = 'translateX(120vw)';
    overlay.style.display = 'flex';
    content.style.opacity = '1';
    setTimeout(() => content.style.transform = 'translateX(0)', 10);
}

/**
 * Generates the HTML for the subtasks of a task.
 * @param {Task} toDo Task record to render.
 * @returns {string} - HTML string representing the subtasks.
 */
function getSubtask(toDo) {
    return toDo.subcategory.map((subtask, index) => getSubtaskCheckboxHTML(toDo, subtask, index)).join('');
}

/**
 * Builds a labelled checkbox with safely escaped subtask text.
 * @param {Task} task Task record.
 * @param {string} text text.
 * @param {number} index Zero-based list index.
 * @returns {string} Rendered markup or text.
 */
function getSubtaskCheckboxHTML(task, text, index) {
    const disabled = canCurrentUserModifyTask(task) ? '' : 'disabled';
    const checked = task.completedSubtasks[index] === 'true' ? 'checked' : '';
    return renderHtmlTemplate('subtaskCheckboxHTMLTemplate', [index, index, task.id, checked, disabled, index, escapeTaskText(text)]);
}

/**
 * Toggles the completion status of a subtask and updates the task.
 * @async
 * @param {number} i Zero-based list index.
 * @param {string} id Database or DOM identifier.
 * @returns {Promise<void>} Resolves when the operation is complete.
 */
async function addCompletedSubtasks(i, id) {
    const task = tasks.find(item => item.id === id);
    if (!canCurrentUserModifyTask(task)) return;
    task.completedSubtasks[i] = task.completedSubtasks[i] === 'false' ? 'true' : 'false';
    await changeTask(`/task/${id}/completedSubtasks`, task.completedSubtasks);
    renderTasks();
}

/**
 * Updates the progress bar for a task or hides it if totalSubtasks is 0.
 * @param {number} subtasksCompleted subtasks Completed.
 * @param {number} totalSubtasks total Subtasks.
 * @param {number} i Zero-based list index.
 * @returns {void}
 */
function updateProgressBar(subtasksCompleted, totalSubtasks, i) {
    const bar = document.getElementById(`progressBarId${i}`);
    if (!bar) return;
    const container = bar.closest('.progressbar');
    if (container) container.style.display = totalSubtasks ? 'flex' : 'none';
    if (totalSubtasks) bar.style.width = `${subtasksCompleted / totalSubtasks * 100}%`;
}

/**
 * Attaches event listeners to task cards to show an overlay when clicked.
 * @returns {void}
 */
function on() {
    const overlay = document.getElementById("overlay");
    const overlayContent = document.querySelector(".overlayContent");
    const tasks = document.querySelectorAll(".card");
    tasks.forEach(task => {
            task.addEventListener("click", () => {
                    revealTaskOverlay(overlay, overlayContent);
                });
        });
}

/**
 * Clears the content of all overlay containers that have an ID containing 'edit-task-overlay'.
 * @returns {void}
 */
function clearEditTaskOverlayContent() {
    const overlayContainers = document.querySelectorAll('[id*="edit-task-overlay"]');
    overlayContainers.forEach(container => {
            container.innerHTML = '';
        });
}

/**
 * Hides the overlay by applying fade-out and slide-out animations.
 * @returns {void}
 */
function off() {
    restoreTaskDialogFocus();
    clearEditTaskOverlayContent();
    animateTaskDialogClose(document.getElementById('overlay'), document.querySelector('.overlayContent'));
    selectedSubtasks = [];
}

/**
 * Returns the icon path based on the task priority.
 * @param {string} priority priority.
 * @returns {string} - The path to the corresponding priority icon.
 */
function getPriorityIcon(priority) {
    switch (priority) {
        case 'urgent':
            return './assets/img/urgent.png';
        case 'medium':
            return './assets/img/medium.png';
        case 'low':
            return './assets/img/low.png';
        default:
            return '';
    }
}
