/** Returns the board-card markup for one task.
 * @param {Task} toDo Task record to render.
 * @param {number} i Zero-based list index.
 * @param {string} taskTypeBackgroundColor Task category color.
 * @param {string} taskType Task category label.
 * @param {string} taskAssignee Rendered assignee avatars.
 * @param {string} taskPriorityIcon Priority icon URL.
 * @param {number} completedSubtasks Number of completed subtasks.
 * @param {string[]} editSubtask Editable subtask labels.
 * @param {string} id Database or DOM identifier.
 * @param {string} subtaskHTML Rendered subtask markup.
 * @returns {string} get task template result.
 */
function getTaskTemplate(toDo, i, taskTypeBackgroundColor, taskType, taskAssignee, taskPriorityIcon, completedSubtasks, editSubtask, id, subtaskHTML) {
    const isDraggable = canCurrentUserModifyTask(toDo);
    return renderHtmlTemplate('taskTemplate', [isDraggable, id, id, taskTypeBackgroundColor, escapeTaskText(taskType), escapeTaskText(toDo.title), escapeTaskText(toDo.description), getTaskProgressHTML(i, completedSubtasks, toDo.subcategory.length), taskAssignee, taskPriorityIcon, escapeTaskText(toDo.prio)]);
}

/** Returns the subtask progress markup for a task card.
 * @param {number} index Zero-based list index.
 * @param {number} completed completed.
 * @param {number} total total.
 * @returns {string} Rendered markup or text.
 */
function getTaskProgressHTML(index, completed, total) {
    return renderHtmlTemplate('taskProgressHTMLTemplate', [index, completed, total]);
}

/** Returns editable markup for every supplied subtask.
 * @param {string[]} editSubtask Editable subtask labels.
 * @returns {string} Rendered markup or text.
 */
function getEditSubtaskHTML(editSubtask) {
    return editSubtask.map(getSubcategoryEditorHTML).join('');
}

/** Adds empty-state placeholders to board columns without tasks.
 * @returns {void}
 */
function checkIfEmpty() {
    const messages = { triage: 'No tasks in Triage', toDo: 'No tasks To do',
        progress: 'Nothing in progress', feedback: 'No tasks awaiting feedback',
        done: 'No tasks done' };
    Object.entries(messages).forEach(([id, message]) => renderEmptyColumn(id, message));
}

/** Renders one empty-board-column placeholder when required.
 * @param {string} id Database or DOM identifier.
 * @param {string} message Feedback text; an empty string clears the error.
 * @returns {void}
 */
function renderEmptyColumn(id, message) {
    const column = document.getElementById(id);
    if (column?.innerHTML.trim() !== '') return;
    column.innerHTML = renderHtmlTemplate('renderEmptyColumnTemplate', [message]);
}

/** Returns the complete task-detail overlay markup.
 * @param {string} taskTitle task Title.
 * @param {string} taskDescription task Description.
 * @param {string} taskDueDate task Due Date.
 * @param {string} taskPriority task Priority.
 * @param {string} taskPriorityIcon Priority icon URL.
 * @param {string} taskType Task category label.
 * @param {string} taskTypeBackgroundColor Task category color.
 * @param {string} assigneeOverlayContent assignee Overlay Content.
 * @param {string} subtaskHTML Rendered subtask markup.
 * @param {string} id Database or DOM identifier.
 * @param {Object} taskCreator Saved creator metadata.
 * @param {boolean} aiGenerated Whether the task was generated by AI.
 * @param {Array<*>} attachments Images with their saved metadata and base64 data.
 * @returns {*} get overlay template result.
 */
function getOverlayTemplate(taskTitle, taskDescription, taskDueDate, taskPriority, taskPriorityIcon, taskType, taskTypeBackgroundColor, assigneeOverlayContent, subtaskHTML, id, taskCreator, aiGenerated, attachments = []) {
    const creatorName = taskCreator?.name || taskCreator?.email || 'Unknown';
    const creator = getCreatorOverlayParts(taskCreator, creatorName);
    const aiBadge = getAiBadgeHTML(aiGenerated);
    const taskActions = getTaskActionsHTML(id, taskCreator);
    return getEditTaskShellHTML(id) + getTaskOverlayHeaderHTML(taskType,
        taskTypeBackgroundColor, aiBadge, taskTitle) + getTaskOverlayDetailsHTML(
        taskDescription, creatorName, creator, taskDueDate, taskPriority,
        taskPriorityIcon, assigneeOverlayContent, subtaskHTML, attachments) + taskActions;
}

/** Returns the hidden edit-task shell embedded in the task overlay.
 * @param {string} id Database or DOM identifier.
 * @returns {string} Rendered markup or text.
 */
function getEditTaskShellHTML(id) {
    return renderHtmlTemplate('editTaskShellHTMLTemplate', [id, id, id, id]);
}

/** Returns category, AI badge, close button, and title for a task overlay.
 * @param {string} type type.
 * @param {string} color Validated CSS color.
 * @param {string} aiBadge ai Badge.
 * @param {string} title title.
 * @returns {string} Rendered markup or text.
 */
function getTaskOverlayHeaderHTML(type, color, aiBadge, title) {
    return renderHtmlTemplate('taskOverlayHeaderHTMLTemplate', [safeTaskColor(color), escapeTaskText(type), aiBadge, escapeTaskText(title)]);
}

/** Returns creator, date, priority, assignees, and subtasks for an overlay.
 * @param {string} description description.
 * @param {string} creatorName creator Name.
 * @param {Object} creator creator.
 * @param {string} date date.
 * @param {string} priority priority.
 * @param {string} icon icon.
 * @param {string} assignees assignees.
 * @param {string} subtasks subtasks.
 * @param {Array<*>} attachments Images with their saved metadata and base64 data.
 * @returns {string} Rendered markup or text.
 */
function getTaskOverlayDetailsHTML(description, creatorName, creator, date,
    priority, icon, assignees, subtasks, attachments = []) {
    return renderHtmlTemplate('taskOverlayDetailsHTMLTemplate', [escapeTaskText(description), creator.badge, escapeTaskText(creatorName), creator.action, escapeTaskText(date), escapeTaskText(priority), icon, escapeTaskText(priority), assignees, getTaskAttachmentsHTML(attachments), subtasks ? renderHtmlTemplate('TaskOverlayDetailsHTMLItemTemplate', [subtasks]) : '']);
}

/** Returns stored task images as safe preview links.
 * @param {Array<*>} attachments Images with their saved metadata and base64 data.
 * @returns {string} Rendered markup or text.
 */
function getTaskAttachmentsHTML(attachments) {
    if (!Array.isArray(attachments) || !attachments.length) return '';
    return renderHtmlTemplate('taskAttachmentsHTMLTemplate', [attachments.map((file, index) => renderHtmlTemplate('TaskAttachmentsHTMLItemTemplate', [index, escapeTaskText(file.name), file.base64, escapeTaskText(file.name), index, escapeTaskText(file.name)])).join('')]);
}

/** Returns creator badge and action markup for a task overlay.
 * @param {Object} creator creator.
 * @param {string} name Display name.
 * @returns {{badge: string, action: string}} Resulting data.
 */
function getCreatorOverlayParts(creator, name) {
    const isExternal = creator?.type === 'external';
    const isGuest = creator?.role === 'guest';
    return { badge: getCreatorBadgeHTML(isExternal, isGuest),
        action: getCreatorActionHTML(creator, name, isExternal, isGuest) };
}

/** Returns internal or external creator badge markup.
 * @param {boolean} isExternal Whether the creator is an external stakeholder.
 * @param {boolean} isGuest Whether the creator is a guest.
 * @returns {string} Rendered markup or text.
 */
function getCreatorBadgeHTML(isExternal, isGuest) {
    if (isExternal) return renderHtmlTemplate('creatorBadgeHTMLTemplate', []);
    const label = isGuest ? 'Guest' : 'Member';
    return renderHtmlTemplate('creatorBadgeHTMLTemplate2', [label]);
}

/** Returns the email or profile action for a task creator.
 * @param {Object} creator creator.
 * @param {string} name Display name.
 * @param {boolean} isExternal Whether the creator is an external stakeholder.
 * @param {boolean} isGuest Whether the creator is a guest.
 * @returns {string} Rendered markup or text.
 */
function getCreatorActionHTML(creator, name, isExternal, isGuest) {
    if (isGuest) return '';
    if (isExternal) return renderHtmlTemplate('creatorActionHTMLTemplate', [escapeTaskText(creator?.email || ''), escapeTaskText(name)]);
    const email = encodeURIComponent(creator?.email || '');
    return renderHtmlTemplate('creatorActionHTMLTemplate2', [email, escapeTaskText(name)]);
}

/** Returns the supplied AI-generated asset when the task was generated by AI.
 * @param {boolean} aiGenerated Whether the task was generated by AI.
 * @returns {string} Rendered markup or text.
 */
function getAiBadgeHTML(aiGenerated) {
    return aiGenerated ? renderHtmlTemplate('aiBadgeHTMLTemplate', []) : '';
}

/** Returns task edit and delete controls for authorized sessions.
 * @param {string} id Database or DOM identifier.
 * @param {Object} taskCreator Saved creator metadata.
 * @returns {string} Rendered markup or text.
 */
function getTaskActionsHTML(id, taskCreator) {
    if (!canCurrentUserModifyTask({ creator: taskCreator })) return '';
    return renderHtmlTemplate('taskActionsHTMLTemplate', [id, id]);
}
